describe('delay', function()
    setup(function()
        delay = require("lib/delay")
        tempo = 120
    end)

    describe('ratio_to_ms()', function()
        it('converts ratios to ms at the given tempo', function()
            assert.same(500, delay.ratio_to_ms('1/4', tempo))
            assert.same(250, delay.ratio_to_ms('1/8', tempo))
            assert.same(375, delay.ratio_to_ms('1/8.', tempo))
            assert.same(125, delay.ratio_to_ms('1/16', tempo))
        end)
    end)

    describe('options()', function()
        it('returns a table of delay times', function()
            local opt = delay.options()
            assert.same('1/128', opt[1])
            assert.same('1/16.', opt[7])
            assert.same('1', opt[14])
        end)
    end)
end)
