describe('Menu', function()
    setup(function()
        menu = require("lib/menu")
    end)

    describe('new()', function()
        it('should have an initial page', function()
            assert.same('global', menu:new():page())
        end)
    end)

    describe('page()', function()
        it('should have a page for each menu item', function()
            assert.same('global', menu:new('tempo'):page())
            assert.same('global', menu:new('swing'):page())
            assert.same('track', menu:new('track_sample'):page())
            assert.same('step', menu:new('step_sample'):page())
            assert.same('step', menu:new('step_offset'):page())
            assert.same('step', menu:new('step_velocity'):page())
        end)
    end)

    describe('select_track()', function()
        it('switches to the track page', function()
            local m = menu:new('tempo')
            m:select_track()
            assert.same('track', m:page())
        end)
    end)
end)
